Homework 2
samuellucic/android-vjestina-tmdb pull request #2
Opened 2023-04-04 21:43 UTC by samuellucic

2023-04-11 16:15 UTC, pero18 commented
Before I review your homework, please merge the first PR, then rebase branch `homework-2` to main, and then push those changes.  You can find detailed instructions on this in `git_basics` file.

2023-04-12 13:53 UTC, pero18 requested changes
Magic numbers should be moved to top-level constants and they should be given meaningful names. Also all the strings that appear in app should be moved to strings file. Same goes for dimensions (like dimens of cards). 
Seems that something went wrong while rebasing because this PR contains changes from the first homework and that shouldn't be the case.  Please rebase homework-2 to main again, this should resolve this problem.

Homework is well written but you can improve some stuff, please request the review once you have done it.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/favorites/FavoritesScreen.kt
> +    Column(
There is no need for a `Column` here, you can use LazyVerticalGrid instead and wrap Favorites text with `item` function.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/favorites/mapper/FavoritesMapperImpl.kt
> +                .asSequence()
You are creating 2 new objects here, first a sequence and then a list. Since the favorites list will probably be small in most cases this will actually decrease the performance.  Optimizations like this shouldn't be done at first, you should write the program as simple as possible, and then see what parts of the code are slow and should be improved. This probably wouldn't be one of those.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/HomeScreen.kt
> +    onFavoriteChange: () -> Unit,
it seems like you are missing `onCategoryClick` argument which should change `selectedMovieCategory`.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/HomeScreen.kt
> +            title = "Trending movies",
Texts should never be hardcoded, use string already defined in strings file, or define one yourself if it isn't already defined.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/HomeScreen.kt
> +                            }
problem with defining this behavior here is that you are mutating the value passed to MovieCategoryScreen function and not the viewState itself. This method should be defined in the same place where the viewState is defined.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/HomeScreen.kt
> +        Row(
This implementation work only when all items fit the screen. Make it more robust, to work on all screen sizes and no matter how long or how many items there are.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/HomeScreen.kt
> +                            0, 1 -> {
Here you are hardcoding numbers, if you change the order of MovieCategories, this won't work. Use ordinal and avoid using else, because this will just mask the problem.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/HomeScreen.kt
> +        LazyHorizontalGrid(
I believe lazyRow is more appropriate here. This should also make this `height(230.dp)` redundant.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/mapper/HomeScreenMapperImpl.kt
> +import android.content.res.Resources
This import is unused. You should always optimize imports and use auto reformat before commiting.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/mapper/HomeScreenMapperImpl.kt
> +            movieCategories = movieCategories.asSequence()
Since there are only 4 categories this is definitely an overkill. I suggest you don't transform list to sequences unless you are absolutely sure it will optimize your code. This will usually hold up only when the list is really big and when they are a couple operations on it. When you are just using map lists should be faster even when they are large.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/main/MainScreen.kt
> +    var showBottomBar by remember { mutableStateOf(true) }
this state should be derived from `navBackStackEntry`, you  can decide whether you want to show bottom bar based on `destination`. By doing this you don't have to change it manually every time you change the screen. This nicely encapsulates this logic in one place and you don't have to worry about it if you decide to add another tab or screen.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/main/MainScreen.kt
> +    Box(
You could use TopAppBar here, but this should be fine as well.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/main/MainScreen.kt
> +            .height(80.dp)
do you need this?

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +    movieDetailsViewState: MovieDetailsViewState,
function should take only arguments that are need. Since it is not using all the properties of `MovieDetailsViewState` you sholdn't pass the entire object.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +                        )
this shouldn't be hardcoded. Move them to constant and give them meaningful names.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +                    size = 42.dp,
this should be moved to dimens.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +                    text = "User score",
strings.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +        LazyHorizontalGrid(
Lazy Row would be more appropriate.

2023-04-12 13:53 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +            modifier = Modifier
Check out contentPadding and try to use it here.

2023-04-21 08:03 UTC, samuellucic commented on app/src/main/java/endava/codebase/android/movieapp/ui/favorites/mapper/FavoritesMapperImpl.kt
> +                .asSequence()
Should I change the other mappers or just this one?

2023-04-21 12:38 UTC, samuellucic commented on app/src/main/java/endava/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +    movieDetailsViewState: MovieDetailsViewState,
Do I need to create a new data class?

2023-04-21 12:44 UTC, samuellucic commented on app/src/main/java/endava/codebase/android/movieapp/ui/main/MainScreen.kt
> +    var showBottomBar by remember { mutableStateOf(true) }
Do you mean that I should  just reassign the showBottomBar variable somewhere below so it gets reevaluated on every rerender?

2023-04-25 09:38 UTC, pero18 reviewed
Looks good, please take a look at the comments I have left you, once you resolve them you can merge your homework!

2023-04-25 09:38 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/favorites/mapper/FavoritesMapperImpl.kt
> +        favoriteMovies.forEach { favoriteMovie ->
instead of creating a  `mutableList`  and then adding elements to it, take a look at `List.map` function

2023-04-25 09:38 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/mapper/HomeScreenMapperImpl.kt
> +        movieCategories.forEach { movieCategory ->
use 'List.map' function same thing for creating homeMovieViewStates

2023-04-25 09:38 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/main/MainScreen.kt
> +    var showBottomBar by remember { mutableStateOf(true) }
No, you can do something like this

```
val showBottomBar by remember {
        derivedStateOf {
            when (navBackStackEntry?.destination?.route) {
                /* add your code here */
            }
        }
    }
```

With the code above showBottomBar will reevaluated every time `navBackStackEntry.destination.route` changes. This way you don't have to change it manually every time the stack changes.

2023-04-25 09:38 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +    movieDetailsViewState: MovieDetailsViewState,
No, just pass the ones you need individually.

2023-04-25 16:32 UTC, merged