Homework 3
samuellucic/android-vjestina-tmdb pull request #3
Opened 2023-04-23 15:08 UTC by samuellucic

2023-04-28 13:10 UTC, pero18 requested changes

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/MovieApp.kt
> +                movieDetailsModule,
You are missing dataModule here.

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/data/repository/MovieRepository.kt
> +    suspend fun toggleFavorite(movieId: Int)
Just a suggestion but the code is usually more readable when you add empty space between methods.

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/data/repository/FakeMovieRepository.kt
> +                )
`data class` has a `copy` method try to use it here.
Since kotlin has a lot of functional language constructs (where mutating variables isn't possible), and `data class` are quite heavily used in Android programming this is a very important function, because it allows us to concisely create a new object with some of the properties changed.

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/data/repository/FakeMovieRepository.kt
> +                    cast = movieDetails.cast,
again try to do this using the `copy function`. 
Hint, it can be done in 2 lines.

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/favorites/FavoritesViewModel.kt
> +    private fun generateFavorites() {
Instead of doing this in `init` block we can do it directly during variable initialization.
val favoritesViewState: StateFlow<...> = movieRepository.favoriteMovies().map(...).stateIn(...)
Because of this you can remove `_favoritesViewState` because it becomes redundant.

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/favorites/FavoritesViewModel.kt
> +    private fun generateFavorites() {
You should really think of a flow as a pipe, from which you don't want to collect (take anything out) until you come to the end , where it should be used. Here you are are using `collect` which reads everything emitted to flow and then you emit it to another flow, this is just extra work we shouldn't do.
Good thing about flow is that it offers a lot of methods which can mutate it so we don't have to read anything from it until we actually need to use it (in fragment).

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/favorites/di/FavoritesModule.kt
> +    includes(dataModule)
no need to include dataModule here, all modules should just be defined in `modules` block.

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/HomeScreen.kt
> +            onFavoriteChange = { movieId ->
insteead of creating a lambda here use method reference. ALso you should use it whenever possible.

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/HomeScreen.kt
> +                viewModel.changeCategory(categoryId)
method reference

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/HomeViewModel.kt
> +    }
again you can avoid this extra property and `init` block by using `map` method and `flapMapLatest` method.

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/HomeViewModel.kt
> +    fun changeCategory(categoryId: Int) {
you should add 2 properties, which will hold the selected category. Something like `trendingMoviesCategorySelected` and then this method should only mutate those flows, and then you will use that flow to generate viewState.

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/di/HomeModule.kt
> +    includes(dataModule)
.

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +        onFavoriteChange = { viewModel.toggleFavorite() },
method reference.

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/moviedetails/MovieDetailsViewModel.kt
> +    init {
.

2023-04-28 13:10 UTC, pero18 commented on app/src/main/java/endava/codebase/android/movieapp/ui/moviedetails/di/MovieDetailsModule.kt
> +    includes(dataModule)
.

2023-05-02 22:18 UTC, samuellucic commented on app/src/main/java/endava/codebase/android/movieapp/ui/home/HomeViewModel.kt
> +    }
Is the flatMapLatest used for favorite click or category change or both?

2023-05-04 17:08 UTC, pero18 approved these changes

2023-05-06 15:32 UTC, merged